version: "3"

services:
  scraping-app:
    container_name: scraping-back
    restart: always
    build: .
    ports:
    - "5000:5000"
    volumes:
     - .:/usr/src/app
    command: nodemon --legacy-watch app.js